spring:
  application:
    name: DEVICE-SERVICE

  #Mysql database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/device-db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  #rabbitMQ configuration
  rabbitmq:
    addresses: localhost:5672

  #Zipkin and sleuth configuration
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #tracing 100% of the requests
      probability: 1.0

server:
  port: 9090

#spring boot actuator health metrics activate
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      history:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  #resilience4j Timeout Properties
  timelimiter:
    instances:
      history:
        timeout-duration: 3s
  #resilience4j Retry Properties
  retry:
    instances:
      history:
        inventory:
          max-attempts: 3
          wait-duration: 5s

#eureka discovery config
### --- will be fetched from Config Server